# Generated by Django 5.2 on 2025-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='product',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.FloatField(),
        ),
    ]
